### ISSUE TITLE
FR: Remove non exist local file.

### ISSUE THREAD

**Issue by ikeji** [dmathieu/glynn#38]
Hi,

I found the file removed locally is NOT removed in remote.

Steps to reproduce.
1. Create a file in local.
2. Run glynn command to sync.
3. Remove the file which is created in step 1.
4. Run glynn command to sync.

Expected:
Removed the file.

Actual:
Glynn never remove the file.

Can we have a option to remove the file which is not exist on local?

**Comment by dmathieu** [comment]
Yes, this is a known behavior.
Feel free to open a pull request if you wish to change it.

**Comment by tassoman** [comment]
A short hack could be deleting all the remote tree, then re-uploading the necessary files/dirs :question:

**Comment by dmathieu** [comment]
This is not a good solution. If you have large files or a big number of them, it means your app would send 404s for some quite time. We should loop through all distant files and remove them if they're not used locally anymore.

**Comment by ricardovsilva** [comment]
Since we need to download all files from server to verify which are differen,. I'm thinking about create a PR to solve that problem and adopt the follow strategy:

1. Create some file, something like _hashes, and store md5 or sha1 of each file inside that. If this file don't exists, we create that, store hashes and upload everything to server (including this file).
2. Everytime glynn runs, download that file and verify which hashes exists, calculate the hash of each file to upload and don't upload files with same hash. Update _hashes file and upload it also.

This still don't automatically deleting files from server, but, at least solves the problem that each file is uploaded everytime.

**Comment by dmathieu** [comment]
@ricardovsilva I like your idea. A PR would be most welcome.
Deleting non-existant files is not really the same issue though. But solving it should actually be easier. Loop through all files on the server, and check if the same file exists locally. If it doesn't, delete it.

**Comment by ricardovsilva** [comment]
Comming back at this. Now I'm working with Grunt with ftpush. Some people prefer Gulp. At all, for me glynn makes no sense anymore.

**Comment by ikeji** [comment]
Thanks all!
